version: "3.3"
services:
  nginx:
    image: nginx:1.19.5-alpine
    container_name: nginx
    restart: 'always'
    networks:
      frontend-web:
        ipv4_address: 172.19.0.5
      backend-web:
    ports:
      - "80:80"
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ../public:/srv/http
      - ./nginx/sites:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime:ro
      - ../public/wordpress:/var/www/html
    links:
      - php8-fpm
      - php7-fpm
      - php5-fpm
      - db
  php8-fpm:
    image: rleutz/php:8.0-fpm
    build: ./build/php8-fpm
    container_name: php8-fpm
    restart: 'always'
    networks:
      - backend-web
    volumes:
      - ../public:/srv/http/
      - /etc/localtime:/etc/localtime:ro
  php7-fpm:
    image: rleutz/php:7.4-fpm
    build: ./build/php7-fpm
    container_name: php7-fpm
    restart: 'always'
    networks:
      - frontend-web
      - backend-web
    volumes:
      - ../public:/srv/http
      - /etc/localtime:/etc/localtime:ro
  php5-fpm:
    image: rleutz/php:5.6-fpm
    build: ./build/php5-fpm
    container_name: php5-fpm
    restart: 'always'
    networks:
      - frontend-web
      - backend-web
    volumes:
      - ../public:/srv/http
      - /etc/localtime:/etc/localtime:ro
  wp-dev:
    depends_on:
      - db
    container_name: wp-dev
    image: wordpress:latest
    restart: 'always'
    networks:
      - frontend-web
      - backend-web
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp-dev
      WORDPRESS_DB_PASSWORD: senha123
      WORDPRESS_DB_NAME: wp-dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../public/wordpress:/var/www/html
  db:
    image: bitnami/mariadb:10.5-debian-10
    container_name: db
    restart: 'always'
    ports:
      - '3306'
    networks:
      - backend-web
    environment:
      MARIADB_REPLICATION_MODE: master
      MARIADB_REPLICATION_USER: repl_user
      MARIADB_REPLICATION_PASSWORD: repl_senha123
      MARIADB_ROOT_PASSWORD: senha123
      MARIADB_DATABASE: wp-dev  
      MARIADB_USER: wp-dev
      MARIADB_PASSWORD: senha123
    volumes:
       - ./database/master:/bitnami/mariadb
       - /etc/localtime:/etc/localtime:ro
  db-backup:
    image: bitnami/mariadb:10.5-debian-10
    container_name: db-backup
    restart: 'always'
    ports:
      - '3306'
    networks:
      - backend-web
    depends_on:
      - db
    environment:
      MARIADB_REPLICATION_MODE: slave
      MARIADB_REPLICATION_USER: repl_user
      MARIADB_REPLICATION_PASSWORD: repl_senha123
      MARIADB_MASTER_HOST: db
      MARIADB_MASTER_PORT: 3306
      MARIADB_MASTER_ROOT_PASSWORD: senha123
    volumes:
      - ./database/backup:/bitnami/mariadb
      - /etc/localtime:/etc/localtime:ro
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    container_name: phpmyadmin
    networks:
      - backend-web
    environment:
      PMA_ARBITRARY: 1
networks:
  frontend-web:
    internal: false
    ipam:
      config:
        - subnet: 172.19.0.0/24
  backend-web:
    internal: true
    ipam:
      config:
        - subnet: 172.20.0.0/24
