version: "3.9"
services:
  nginx:
    image: nginx:1.19.5-alpine
    container_name: nginx
    restart: 'always'
    networks:
      - frontend-web
      - backend-web
    ports:
      - "80:80"
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-public:/srv/http
      - ./nginx/sites:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime:ro
      - ./nginx-public/wordpress:/var/www/html
    links:
      - php8-fpm
      - php7-fpm
      - php5-fpm
      - db
  php8-fpm:
    image: rleutz/php:8.0-fpm
    build: ./build/php8-fpm
    container_name: php8-fpm
    restart: 'always'
    networks:
      - backend-web
    volumes:
      - ./nginx-public:/srv/http/
      - /etc/localtime:/etc/localtime:ro
  php7-fpm:
    image: rleutz/php:7.4-fpm
    build: ./build/php7-fpm
    container_name: php7-fpm
    restart: 'always'
    networks:
      -frontend-web
      - backend-web
    volumes:
      - ./nginx-public:/srv/http
      - /etc/localtime:/etc/localtime:ro
  php5-fpm:
    image: rleutz/php:5.6-fpm
    build: ./build/php5-fpm
    container_name: php5-fpm
    restart: 'always'
    networks:
      - frontend-web
      - backend-web
    volumes:
      - ./nginx-public:/srv/http
      - /etc/localtime:/etc/localtime:ro
  wp-dev:
    depends_on:
      - db
    container_name: wp-dev
    image: wordpress:latest
    restart: 'always'
    networks:
      - frontend-web
      - backend-web
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp-dev
      WORDPRESS_DB_PASSWORD: senha123
      WORDPRESS_DB_NAME: wp-dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx-public/wordpress:/var/www/html
  db:
    image: mariadb:10.5
    container_name: db
    restart: 'always'
    networks:
      - backend-web
    environment:
       MYSQL_ROOT_PASSWORD: senha123
       MYSQL_DATABASE: wp-dev  
       MYSQL_USER: wp-dev
       MYSQL_PASSWORD: senha123
    volumes:
       - ./database:/var/lib/mysql
       - /etc/localtime:/etc/localtime:ro
networks:
  frontend-web:
    internal: false
  backend-web:
    internal: true
